// Generated by scripts/generate-protocol.mjs. Do not edit manually.

export const PROTOCOL_VERSION = "1.2" as const;

export type RequestId = number | string;

export interface ImplementationInfo {
  name: string;
  version: string;
}

export interface ClientCapabilities {
  cancellation?: boolean;
}

export interface ServerCapabilities {
  cancellation: boolean;
  repositoryDiscovery: boolean;
  workingTreeStatus: boolean;
}

export interface InitializeParams {
  clientInfo: ImplementationInfo;
  protocolVersion: string;
  capabilities?: ClientCapabilities;
}

export interface InitializeResult {
  coreInfo: ImplementationInfo;
  protocolVersion: string;
  capabilities: ServerCapabilities;
}

export interface CancelParams {
  id: RequestId;
}

export interface ErrorData {
  stableCode: string;
  retryable: boolean;
  details?: Record<string, unknown>;
}

export interface RepositoryPathParams {
  path: string;
}

export type RepositoryKind = "worktree" | "linkedWorktree" | "bare";

export interface RepositoryDescriptor {
  worktreeRoot: string | null;
  gitDirectory: string;
  commonGitDirectory: string;
  kind: RepositoryKind;
  gitVersion: string;
}

export type StatusEntryKind = "ordinary" | "renameOrCopy" | "unmerged" | "untracked";

export type FileStatus = "unmodified" | "modified" | "added" | "deleted" | "renamed" | "copied" | "unmerged" | "untracked" | "typeChanged" | "unknown";

export interface StatusEntry {
  path: string;
  originalPath: string | null;
  kind: StatusEntryKind;
  indexStatus: FileStatus;
  worktreeStatus: FileStatus;
}

export interface BranchStatus {
  head: string | null;
  oid: string | null;
  upstream: string | null;
  ahead: number;
  behind: number;
}

export interface WorkingTreeStatus {
  branch: BranchStatus;
  entries: StatusEntry[];
}
