// Generated by scripts/generate-protocol.mjs. Do not edit manually.

export const PROTOCOL_VERSION = "1.10" as const;

export type RequestId = number | string;

export interface ImplementationInfo {
  name: string;
  version: string;
}

export interface ClientCapabilities {
  cancellation?: boolean;
}

export interface ServerCapabilities {
  cancellation: boolean;
  repositoryDiscovery: boolean;
  workingTreeStatus: boolean;
  structuredFileDiff: boolean;
  paginatedCommitHistory: boolean;
  structuredCommitDiff: boolean;
  repositoryReferences: boolean;
  commitGraphProjection: boolean;
  githubRepository: boolean;
  githubPullRequest: boolean;
  githubPullRequestCommitDiff: boolean;
}

export interface InitializeParams {
  clientInfo: ImplementationInfo;
  protocolVersion: string;
  capabilities?: ClientCapabilities;
}

export interface InitializeResult {
  coreInfo: ImplementationInfo;
  protocolVersion: string;
  capabilities: ServerCapabilities;
}

export interface CancelParams {
  id: RequestId;
}

export interface ErrorData {
  stableCode: string;
  retryable: boolean;
  details?: Record<string, unknown>;
}

export interface RepositoryPathParams {
  path: string;
}

export type RepositoryKind = "worktree" | "linkedWorktree" | "bare";

export interface RepositoryDescriptor {
  worktreeRoot: string | null;
  gitDirectory: string;
  commonGitDirectory: string;
  kind: RepositoryKind;
  gitVersion: string;
}

export type StatusEntryKind = "ordinary" | "renameOrCopy" | "unmerged" | "untracked";

export type FileStatus = "unmodified" | "modified" | "added" | "deleted" | "renamed" | "copied" | "unmerged" | "untracked" | "typeChanged" | "unknown";

export interface StatusEntry {
  path: string;
  originalPath: string | null;
  kind: StatusEntryKind;
  indexStatus: FileStatus;
  worktreeStatus: FileStatus;
}

export interface BranchStatus {
  head: string | null;
  oid: string | null;
  upstream: string | null;
  ahead: number;
  behind: number;
}

export interface WorkingTreeStatus {
  branch: BranchStatus;
  entries: StatusEntry[];
}

export type DiffScope = "workingTree" | "staged";

export interface DiffParams {
  path: string;
  scope: DiffScope;
  contextLines?: number;
}

export type DiffLineKind = "context" | "addition" | "deletion";

export interface DiffLine {
  kind: DiffLineKind;
  content: string;
  oldLine: number | null;
  newLine: number | null;
}

export interface DiffHunk {
  oldStart: number;
  oldLines: number;
  newStart: number;
  newLines: number;
  header: string;
  lines: DiffLine[];
}

export interface FileDiff {
  oldPath: string;
  newPath: string;
  isBinary: boolean;
  hunks: DiffHunk[];
}

export interface HistoryParams {
  limit?: number;
  cursor?: string;
}

export interface CommitIdentity {
  name: string;
  email: string;
  timestamp: string;
}

export interface CommitSummary {
  oid: string;
  parents: string[];
  author: CommitIdentity;
  committer: CommitIdentity;
  summary: string;
  message: string;
}

export interface HistoryPage {
  commits: CommitSummary[];
  nextCursor: string | null;
}

export interface CommitDiffParams {
  oid: string;
  parentOid?: string;
  contextLines?: number;
}

export interface CommitDiff {
  commit: CommitSummary;
  parentOid: string | null;
  files: FileDiff[];
}

export type ReferenceKind = "localBranch" | "remoteBranch" | "tag";

export interface RepositoryHead {
  oid: string | null;
  symbolicRef: string | null;
}

export interface RepositoryReference {
  name: string;
  fullName: string;
  kind: ReferenceKind;
  targetOid: string;
  peeledTargetOid: string | null;
  symbolicTarget: string | null;
  upstream: string | null;
}

export interface RepositoryReferences {
  head: RepositoryHead;
  references: RepositoryReference[];
}

export interface CommitGraphNode {
  commit: CommitSummary;
  isHead: boolean;
  references: RepositoryReference[];
}

export interface CommitGraphPage {
  nodes: CommitGraphNode[];
  nextCursor: string | null;
}

export interface GitHubRepositoryParams {
  remote?: string;
  nameWithOwner?: string;
}

export interface GitHubRepository {
  host: "github.com";
  owner: string;
  name: string;
  nameWithOwner: string;
  url: string;
  defaultBranch: string;
  isPrivate: boolean;
}

export interface GitHubPullRequestParams {
  number: number;
  remote?: string;
  nameWithOwner?: string;
}

export type GitHubPullRequestState = "open" | "closed" | "merged";

export interface GitHubPullRequestRef {
  name: string;
  oid: string;
  repository: string | null;
}

export interface GitHubCommitIdentity {
  name: string;
  email: string;
  timestamp: string;
  login: string | null;
}

export interface GitHubPullRequestCommit {
  oid: string;
  parents: string[];
  author: GitHubCommitIdentity;
  committer: GitHubCommitIdentity;
  summary: string;
  message: string;
  url: string;
}

export interface GitHubPullRequest {
  host: "github.com";
  nameWithOwner: string;
  number: number;
  title: string;
  body: string | null;
  state: GitHubPullRequestState;
  isDraft: boolean;
  authorLogin: string | null;
  url: string;
  createdAt: string;
  updatedAt: string;
  closedAt: string | null;
  mergedAt: string | null;
  base: GitHubPullRequestRef;
  head: GitHubPullRequestRef;
  mergeCommitOid: string | null;
  commits: GitHubPullRequestCommit[];
}

export interface GitHubPullRequestCommitDiffParams {
  number: number;
  oid: string;
  remote?: string;
  nameWithOwner?: string;
}

export type GitHubFileStatus = "added" | "removed" | "modified" | "renamed" | "copied" | "changed" | "unchanged";
export type GitHubPatchState = "available" | "unavailable";

export interface GitHubCommitFileDiff {
  oldPath: string;
  newPath: string;
  status: GitHubFileStatus;
  additions: number;
  deletions: number;
  changes: number;
  patchState: GitHubPatchState;
  hunks: DiffHunk[];
}

export interface GitHubPullRequestCommitDiff {
  host: "github.com";
  nameWithOwner: string;
  pullRequestNumber: number;
  commit: GitHubPullRequestCommit;
  files: GitHubCommitFileDiff[];
}
